- name: Install snapd
  apt:
     name: snapd
     state: present

- name: Install core snap
  command: snap install core

- name: Install certbot
  command: snap install --beta --classic certbot

-  name: Trust plugin
   command: snap set certbot trust-plugin-with-root=ok

-  name: Install certbot Cloudflare DNS plugin
   command: snap install --beta certbot-dns-cloudflare

-  name: Prepare plugin
   command: snap connect certbot:plugin certbot-dns-cloudflare

-  name: Create symlink to certbot
   file:
     src: /snap/bin/certbot
     dest: /usr/bin/certbot
     state: link
     force: yes

- name: Obtain a cert and set up with apache
  command: certbot certonly --verbose --dns-cloudflare --dns-cloudflare-credentials /home/{{main_user_name}}/cloudflare.ini -d {{ domain}} -d www.{{ domain }} -m {{ admin_user_name }}@{{ domain }} --agree-tos --non-interactive --dns-cloudflare-propagation-seconds 600

